### ISSUE TITLE
System.Web is not supported by SQLCLR

### ISSUE THREAD

**Issue by simgreci** [simgreci/SQLXEtoEventHub#8]
System.Web used by Microsoft.ServiceBus.Messaging is not supported by SQLCLR: https://msdn.microsoft.com/en-us/library/ms403279.aspx

We should use direct REST calls to EventHub?

**Comment by MindFlavor** [comment]
Yes the relative API is documented here: [https://msdn.microsoft.com/en-us/library/azure/dn790664.aspx](https://msdn.microsoft.com/en-us/library/azure/dn790664.aspx). I've done something equivalent in RUST [mod.rs](https://github.com/MindFlavor/AzureSDKForRust/blob/master/src/azure/service_bus/event_hub/mod.rs). 

We can use the code shown here [https://azure.microsoft.com/en-us/documentation/articles/service-bus-shared-access-signature-authentication/](https://azure.microsoft.com/en-us/documentation/articles/service-bus-shared-access-signature-authentication/) but IIRC there is a bug somewhere. 

The workflow is this one:

![Authentication workflow](http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-01-68-05/6170.image00.png).

I'll work on it as soon as possible.

**Comment by MindFlavor** [comment]
This is a sample of SAS signature in C# (untested):

``` csharp
public static string GenerateSignature(
    string policyName,
    string sasKey,
    Uri uri,
    TimeSpan duration)
{
    string urlEncoded = System.Net.WebUtility.UrlEncode(uri.ToString());
    string expiry = DateTime.Now.Add(duration).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");

    string strToSign = string.Format("{0:S}\n{1:S}", urlEncoded, expiry);
    var bytesToSign = System.Text.Encoding.UTF8.GetBytes(strToSign);

    System.Security.Cryptography.HMACSHA256 SHA256 = new System.Security.Cryptography.HMACSHA256(Convert.FromBase64String(sasKey));
    string strHash2Base64 = Convert.ToBase64String(SHA256.ComputeHash(bytesToSign));

    string strSig = System.Net.WebUtility.UrlEncode(strHash2Base64);

    string sAuth = string.Format("SharedAccessSignature sr={0:S}&sig={1:S}&se={2:S}&skn={3:S}",
        urlEncoded,
        strSig,
        expiry,
        policyName);

    return sAuth;
} 
```

[EventHub/Publisher.cs](https://github.com/simgreci/SQLXEtoEventHub/blob/mindflavor/SQLXEtoEventHub/EventHub/Publisher.cs) class should have the updated code.

**Comment by MindFlavor** [comment]
Done. The code is pullable from here: [https://github.com/simgreci/SQLXEtoEventHub/commit/7f25ad882d154167e0afc933b2faa69a963d5459](https://github.com/simgreci/SQLXEtoEventHub/commit/7f25ad882d154167e0afc933b2faa69a963d5459). In order to accommodate for the REST implementation I've discarded the EventHub connection string. Now I use the explicit elements:
- `EventHubName`
- `ServiceBusNamespace`
- `PolicyName` 
- `PolicyKey`

So I had to modify the [SQLXEtoEventHubSp/StoredProcedure.cs](https://github.com/simgreci/SQLXEtoEventHub/blob/mindflavor/SQLXEtoEventHubSp/StoredProcedure.cs) class a little. 

The EventHubWriter constructor is now like this:

``` csharp
public EventHubWriter(string EventHubName, string ServiceBusNamespace, string PolicyName, string PolicyKey)
```

More here: [SQLXEtoEventHub/EventHubWriter.cs](https://github.com/simgreci/SQLXEtoEventHub/blob/mindflavor/SQLXEtoEventHub/EventHubWriter.cs)
